### ISSUE TITLE
No bin is created

### ISSUE THREAD

**Issue by seanc** [jamen/lavish#1]
No executable is created, seems like you forgot the property in package.json

**Comment by jamen** [comment]
Right now, Lavish doesn't really do anything but the downloading and symlinking, so you wont really see any features outside of those yet.

But, since this is supposed to be drop-in compatible with `npm install`, it is definitely on the roadmap.

**Comment by seanc** [comment]
Alright, sounds good.

**Comment by jamen** [comment]
Nah, keep this open as reminder, thanks.  :)

**Comment by jamen** [comment]
Done did
