### ISSUE TITLE
Windows symlink error

### ISSUE THREAD

**Issue by ConnorHartley** [jamen/lavish#14]
Can only create symlinks in administrative mode.

e.g
`Error: EPERM: operation not permitted, symlink 'C:\Users\username\.lavish\vue\74b53a17-a211-481f-995c-631d6b23ae55' ->    4'C:\Users\username\Desktop\test\node_modules\vue'ish\test\node_modules\vue'
    at Error (native)`

**Comment by jamen** [comment]
I would say config this instead: http://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7
