### ISSUE TITLE
Better CLI feedback?

### ISSUE THREAD

**Issue by jamen** [jamen/lavish#17]
Right now it uses [blessed](http://npmjs.com/blessed) to create a list of boxes, each box with a name and updating status, where it disappears when everything is finished.

![Installing](https://raw.githubusercontent.com/jamen/lavish/master/docs/usage.gif)

I kind of want to change this though, any ideas, or if I should keep it the same?

**Comment by dustindowell22** [comment]
it'd be cool if it looked the same as npm's installer, considering it is _for_ npm

**Comment by jamen** [comment]
@dustindowell22: Yeah, I did think about that when noting "100% compatible with npm", but I feel like it's the CLI usage that should be compatible, and the UI feedback is kind of free reign with that data.

**Comment by phase** [comment]
Instead of creating a new "window" and clearing it when done, put the information in the main window of the terminal so we can keep the log.

```
$ lavish vue
Installing vue@version
[================] 100% or whatever
```

Keeping this in the console allows you to copy it and show error logs.

**Comment by jamen** [comment]
Counter-argument: You can redirect STDERR if you want to preserve logs in the current system.  There should be no runtime errors anyways, those typically signify internal errors that are uncaught and should never happen (my mistakes!).  Saving the session and writing a new screen is purely for aesthetics and should ultimately be unrelated to most things (including errors), which is why this is not an important issue.

But, in any regard, I agree with @dustindowell22 in making it compatible with npm, which by nature would include @phase's suggestions.

Any ideas if they use a module for it, or if they are doing it manually?  Would be nice to use their module to copy it exactly instead of trying to recreate it manually.
